version: '3'

services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=news_board
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    container_name: 'redis'
    command: redis-server
    ports:
      - '6379:6379'

  web:
    build: .
    restart: always
    container_name: 'news_board_django'
    command: python ./news_board/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - SECRET_KEY=Secret_Key
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=news_board
      - DB_USER=user
      - DB_PASS=password
    ports:
      - '8000:8000'
    depends_on:
      - db

  celery:
    build: .
    container_name: 'news_board_celery'
    command: celery -A news_board worker -l info
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis